import { makeStyles } from "@material-ui/core";
const useStyles = makeStyles(() => ({
  modal: {
    margin: "auto",
    marginTop: "10vh",
    backgroundColor: "rgb(25,27,31)",
    border: "1px solid rgb(33,36,41)",
    boxShadow: "rgb(0 0 0 / 5%) 0 4px 8px 0",
    padding: 0,
    width: "50vw",
    overflow: "hidden auto",
    alignSelf: "center",
    maxWidth: 420,
    maxHeight: "90hv",
    display: "flex",
    flexDirection: "column",
    borderRadius: "20px",
    paddingLeft: "1rem",
    paddingRight: "1rem",
  },
  topPart: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flex: 1,
    // marginRight: "1rem",
  },
  closeButton: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    marginRight: "-0.5rem",
  },
  title: {
    fontWeight: "bold",
  },
  searchInputContiner: {
    // display: "flex",
    // flex: 1,
    // marginLeft:'1rem',
    marginRight: "1rem",
  },
  searchInput: {
    "& fieldset": {
      borderRadius: 20,
      borderColor: "#22252A",
    },
  },
  commonBasesContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 5,
    marginBottom: 5,
    columnGap: 5,
  },
  commonBasesText: {
    fontSize: 16,
    color: "#fff",
  },
  helpOutlineIcon: {
    fontSize: 20,
    color: "#fff",
    backgroundColor: "#26292F",
    borderRadius: "100%",
    padding: "0 !important",
  },
  commenTokenConianer: {
    flexWrap: "wrap",
    display: "flex",
    marginRight: -10,
    marginBottom: 30,
  },
  allTokenContainer: {
    position: "relative",
    height: 249,
    width: "calc(100% + 2rem)",
    marginLeft: "-1rem",
    overflow: "auto",
    willChange: "transform",
    direction: "ltr",
    borderTop: "1px solid #22252A",
  },
  bottomPart: {
    width: "calc(100% + 2rem)",
    borderRadius: "0 0 20px 20px",
    // padding: 20,
    paddingTop: 20,
    paddingBottom: 20,
    backgroundColor: "rgb(33,36,41)",
    borderTop: "1px solid rgb(44,47,54)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "-1rem",
  },
  manageToken: {
    fontFamily: "none",
    color: "rgb(80,144,243)",
    fontWeight: 500,
    "&:hover": {
      backgroundColor: "transparent",
    },
  },
}));
export default useStyles;
