import { makeStyles } from "@material-ui/core";
const useStyles = makeStyles(() => ({
  pageContianer: {
    display: "flex",
    padding: "120px 16px 0",
    alignItems: "center",
    flex: "1 1 0",
    zIndex: 1,
    WebkitBoxAlign: "center",
  },
  root: {
    position: "relative",
    maxWidth: 420,
    width: "100%",
    backgroundColor: "rgb(25,27,31)",
    boxShadow:
      "rgb(0 0 0 / 1%) 0 0 1px, rgb(0 0 0 / 4%) 0 4px 8px, rgb(0 0 0 / 4%) 0 16px 24px, rgb(0 0 0 / 1%) 0 24px 32p",
    borderRadius: 24,
    marginLeft: "auto",
    marginRight: "auto",
    zIndex: 1,
    paddingRight: "1rem",
    paddingLeft: "1rem",
    // paddingTop: "0.5rem",
  },
  title: {
    fontWeight: 500,
    fontSize: 16,
  },
  topPart: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  inputsContainer: {
    // gap: 15,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  swapIconButton: {
    padding: 4,
    borderRadius: 12,
    height: 32,
    width: 32,
    position: "relative",
    marginTop: -14,
    marginBottom: -14,
    backgroundColor: "rgb(33,36,41)",
    border: "4px solid rgb(25,27,31)",
    zIndex: 2,
  },
  swapIcon: {
    color: "#fff",
    fontSize: 20,
  },
  connectWallet: {
    marginTop: 10,
    marginBottom: 10,
    padding: 16,
    textAlign: "center",
    borderRadius: "20px !important",
    outline: "none",
    border: "1px solid transparent",
    textDecoration: "none",
    justifyContent: "center",
    display: "flex",
    flexWrap: "nowrap",
    alignItems: "center",
    position: "relative",
    zIndex: 1,
    willChange: "transform",
    backgroundColor: "rgb(21,61,111,0.44)",
    color: "rgb(80,144,234)",
    fontSize: 16,
    fontWeight: 500,
    "&:hover": {
      backgroundColor: "rgba(19,54,98,0.44)",
      boxShadow: "rgb(19 54 98 / 44%) 0 0 0 1pt",
    },
  },
  settingMenuRoot: {
    overflow: "hidden",
    backgroundColor: "rgb(44,47,54)",
    paddnig: "0px !important",
    boxShadow:
      "rgb(0 0 0 / 1%) 0 0px 1px, rgb(0 0 0 / 4%) 0 4px 8px, rgb(0 0 0 / 4%) 0 16px 24px, rgb(0 0 0 / 1%) 0 24px 32px;",
    border: "1px solid rgb(64,68,79)",
    borderRadius: "12px !important",
    padding: "1rem",
    height: "100%",
    minWidth: "20.125rem",
  },
  settingMenu: {
    position: "absolute",
    top: "43px !important",
    left: "-300px !important",
  },
  settingMenuPaper: {
    backgroundColor: "transparent",
    borderRadius: "12px !important",
  },
}));
export default useStyles;
