import { makeStyles } from "@material-ui/core";
const useStyles = makeStyles(() => ({
  root: {
    width: "90%",
    maxWidth: 1340,
    minHeight: "80vh",
    marginBottom: 60,
    padding: "1rem",
  },
  topPart: {
    display: "flex",
    flexDirection: "column",
    willChange: "transform",
    alignItems: "flex-start",
    justifyContent: "flex-end",
    width: "100%",
    height: "calc(100vh - 180px)",
    paddingBottom: "3%",
    paddingLeft: 100,
  },
  topPartTitle: {
    color: "#fff",
    fontSize: 56,
  },
  topPartDescription: {
    fontWeight: 300,
    maxWidth: 780,
    fontSize: 24,
    color: "#fff",
  },
  mediaContianer: {
    marginTop: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 5,
  },
  mediaIcon: {
    color: "#fff",
  },
  numberInfoContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "4rem 0 8rem",
    marginLeft: "10%",
  },
  numbersInfo: {
    display: "flex",
    // flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    // margin: 0,
  },
  numbersPartContianer: {
    display: "flex",
    flexDirection: "column",
    // position: "relative",
    // alignItems: "center",
    // justifyContent: "center",
    rowGap: 5,
  },
  numbersPartTitle: {
    fontSize: 14,
    fontWeight: 300,
    color: "#fff",
  },
  numbersPartValue: {
    color: "#fff",
    fontSize: 48,
    fontWeight: 700,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    margin: "2rem 6rem",
    width: "100%",
  },
  sectionChild: {
    display: "flex",
    justifyContent: "space-between",
    rowGap: 32,
  },
  sectionChildTextContianer: {
    display: "grid",
    gridAutoRows: "auto",
    rowGap: 16,
  },
  sectionChildTextLink: {
    color: "#fff",
    fontSize: 18,
    overflowWrap: "normal",
    maxWidth: 900,
    fontWeight: 400,
    cursor: "pointer",
  },
  sectionChildTextTitle: {
    maxWidth: 380,
    fontSize: 32,
    color: "#fff",
  },
  sectionChildTextDescription: {
    maxWidth: 390,
    lineHeight: "140%",
    fontWeight: 200,
    fontSize: 20,
    opacity: 0.8,
    color: "rgb(136,141,155)",
  },
  sectionChildImageContianer: {
    marginRight: 12,
    width: 590,
    minHeight: 290,
    display: "flex",
    flexDirection: "column",
    gap: 20,
    backgroundRepeat: "no-repeat",
    border: "1px solid rgba(255,255,255,0.19)",
    padding: "2rem",
    borderRadius: 24,
    boxShadow:
      "rgb(0 0 0 / 2%) 0 0 1px, rgb(0 0 0 / 2%) 0 4px 8px, rgb(0 0 0 / 2%) 0px 16px 24px, rgb(0 0 0 / 2%) 0 24px 32px",
  },
  exploreAll: {
    backgroundColor: "rgba(255, 255, 255, 0.1) !important",
    borderRadius: "12px !important",
    color: "#fff",
  },
  secondSection: {
    display: "flex",
    flexDirection: "column",
    margin: "2rem 6rem",
  },
  secondSectionTitle: {
    marginBottom: 16,
    fontSize: 18,
    overflowWrap: "normal",
    maxWidth: 900,
    fontWeight: 400,
    cursor: "pointer",
    color: "#fff",
  },
  secondSectionChildContainer: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gridTemplateRows: "auto auto",
    rowGap: 32,
    columnGap: 16,
    alignItems: "center",
    width: "100%",
  },
  secondSectionLeftChild: {
    display: "grid",
    gridTemplateRows: "1fr auto",
    gap: 16,
    height: "100%",
  },
  secondSectionLeftTopChild: {
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    border: "1px solid rgba(255, 255, 255, 0.19)",
    flex: 1,
    width: "100%",
    background:
      "url(https://uniswap.org/images/developer.png) 0% 0% / cover no-repeat",
    backgroundRepeat: "no-repeat",
    padding: "1rem",
    borderRadius: 24,
  },
  secondSectionLeftTopChildTextContianer: {
    marginTop: "20%",
    display: "grid",
    gridAutoRows: "auto",
    rowGap: 16,
  },
  secondSectionLeftTopChildTextTitle: {
    maxWidth: 960,
    fontSize: 32,
  },
  secondSectionLeftTopChildTextDescription: {
    fontSize: 20,
    color: "rgb(135,141,155)",
    maxWidth: 592,
    fontWeight: 300,
  },
  secondSectionLeftBottomChild: {
    display: "flex",
    width: "100%",
    padding: 0,
    gap: 16,
    alignItems: "flex-end",
  },
  secondSectionRightChild: {
    maxWidth: 375,
    backgroundColor: "rgba(255,255,255, 0.02)",
    border: "1px solid rgba(255,255,255, 0.19)",
    padding: "2rem",
    borderRadius: 24,
    boxShadow:
      "rgb(0 0 0 / 2%) 0 0 1px, rgb(0 0 0 / 2%) 0 4px 8px, rgb(0 0 0 / 2%) 0 16px 24px, rgb(0 0 0 / 2%) 0 24px 32px",
  },
}));
export default useStyles;
